org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
neo_version=21.1.219
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
mod_id=logisticsnetworks
mod_name=LogisticsNetworks
mod_license=All Rights Reserved
mod_version=1.10.1
mod_group_id=me.almana
mod_authors=AlmanX21
mod_description=High level, extremely lag friendly logistics mod
jei_version=19.27.0.340
mekanism_version=1.21.1-10.7.18.84
ars_nouveau_version=5.11.2.1298
jade_version=15.10.0+neoforge
ae2_version=19.2.17
ftb_teams_version=2101.1.0
emi_version=1.1.22+1.21.1
guideme_version=21.1.1
